name: Build & Release tomer

on:
  workflow_dispatch:
  push:
    tags:
      - "v**" # v1.0.0

jobs:
  prepare:
    name: Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tag value
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "Working tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build-push:
    needs:
      - prepare
    name: Build and Push Docker Image
    if: ${{ needs.prepare.outputs.tag }}
    uses: ./.github/workflows/reusable-build-docker.yaml
    with:
      dockerfile: Dockerfile
      context: .
      image-repo: ghcr.io/boomchanotai/tomer
      image-tag: ${{ needs.prepare.outputs.tag }}
